# Generated by Django 2.2.3 on 2019-07-13 03:29

from django.db import migrations, models
import users.functions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=20, null=True, storage=users.functions.OverwriteStorage(), upload_to=users.functions.user_avatar_path, verbose_name='头像'),
        ),
    ]
