# Generated by Django 2.2.3 on 2019-07-13 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='回答正文')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='最后编辑时间')),
                ('good', models.IntegerField(default=0, verbose_name='*好*')),
                ('bad', models.IntegerField(default=0, verbose_name='*不*')),
            ],
        ),
        migrations.CreateModel(
            name='CommentOfAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
            ],
            options={
                'verbose_name_plural': 'CommentsOfAnswers',
            },
        ),
        migrations.CreateModel(
            name='CommentOfQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
            ],
            options={
                'verbose_name_plural': 'CommentsOfQuestions',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100, verbose_name='问题标题')),
                ('description', models.TextField(verbose_name='问题详细描述')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='最后编辑时间')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tag名称')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('able_modify', models.BooleanField(default=True, verbose_name='可编辑')),
                ('able_answer', models.BooleanField(default=True, verbose_name='可添加回答')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='content.Question')),
            ],
            options={
                'verbose_name_plural': 'QuestionsStatus',
            },
        ),
    ]
