# Generated by Django 2.2.3 on 2019-07-18 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20190718_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentofanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='content.Answer'),
        ),
        migrations.AlterField(
            model_name='commentofanswer',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
