# Generated by Django 2.2.3 on 2019-07-18 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20190718_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentofanswer',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='content.Answer'),
        ),
    ]
